[package]
name = "hello-rocket"
version = "0.0.1"
authors = ["Ivan Lukyanow <i.lukyanov@city-mobil.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"